### ISSUE TITLE
When activated on customer shop no tracking data is transmitted to Google Analytics anymore

### ISSUE THREAD

**Issue by frankmental** [shopwareLabs/google-consent-v2-plugin-sw-6-4#8]
As advised, we installed the plugin on every SW6.4.x shop of our customers.
After activation, one customer complained, that there is no tracking data visible anymore in their Google Analytics Dashboard.

![image_2024-03-14_182201121](https://github.com/shopwareLabs/google-consent-v2-plugin-sw-6-4/assets/142607510/375a6cd6-d93c-4b42-ba29-43dfc52729ff)

When we deactivate the plugin everything is working as before.

For tracking purposes we are using the following plugin: https://store.shopware.com/dtgs888695584742m/google-tag-manager-google-analytics-4-remarketing-sw6.html

Do you see any issues with our setup or why there isn't any tracking data visible while the plugin ist activated?

**Comment by BrocksiNet** [comment]
The plugin you are using should be already "Ready for Consent Mode V2" so I guess there is some conflict between some template that we and the Plugin maybe extend. So I would suggest only using this plugin and ask the plugin vendor how to activate or provide the new required properties to google via that plugin.
